### ISSUE TITLE
Problem running java code

### ISSUE THREAD

**Issue by prubach** [shatgupt/runmycode-ext#13]
The runmycode extension is a brilliant idea for example for checking students' homeworks directly on github instead of checking out etc. however, I have an issue with running Java code from github. It seems that the name of the class is not passed on correctly.
I.e. if I want to run Bowls.java I get:

Failed: CodeToRun.java:3: error: class Bowls is public, should be declared in a file named Bowls.java
public class Bowls {
       ^
1 error

I tested that using for example:
https://github.com/prubach/CP_summer_2018/blob/master/src/pl/waw/sgh/Bowls.java

**Comment by shatgupt** [comment]
@prubach The extension code has been updated to handle Java programs with public classes.
I will soon be updating the backend as well. Please check back in 24 hours.

**Comment by shatgupt** [comment]
The backend is also fixed now.
But looking at your code, it is still not going to work with RunMyCode Online because it uses package. Only standalone code is supported by RMCO.

**Comment by RedBeard41** [comment]
I have just stumbled onto your program and it works great unless the code is in packages.  For my intro programming kids they only have one class programs.  If you go into Github to the java file that you want to run, if it is independent then you can click on the edit button and delete the package designation and run and it will work fine.  Hope that helps.

**Comment by shatgupt** [comment]
> For my intro programming kids they only have one class programs.

So glad to know that my application helps kids learn programming! You made my day! 😃

Since internally the code is run as a single file, it cannot be part of a package (which requires a folder structure). Only self-contained code in a single file is supported.

**Comment by RedBeard41** [comment]
Yeah.  I have them create programs using Intellig which automatically creates packages and then they use gitkraken to visually use source control.  I have them push the entire project so it would be easy for them to clone the intellij project onto another computer.  Then they just track changes to their .java files.  Your program can be used in Github to run the program if they are on a chromebook computer and are unable to run a full blown IDE but still want to demo code.  Thank you for creating it.  I had a real hard time trying to find a work around using online IDEs because some dont support file I/O or are much too complex for setting up a working environment to test code.

**Comment by shatgupt** [comment]
One of the primary aims of the application is to support cases where full compiler installation cannot be done (or not required) and the user just wants to run code and see output. Great to hear it is being fulfilled.

I will see if I can do something about java files with package names so that you can run them as is without editing out the package.

**Comment by shatgupt** [comment]
I have made the changes. Now you can run your standalone Java programs without editing out the package declaration. 🎉 

![screenshot 78](https://user-images.githubusercontent.com/2388644/52693358-c7906280-2f23-11e9-8b88-9ec76cca3c15.png)

**Comment by RedBeard41** [comment]
Wow, that was unexpected, but amazing.  Thanks for all you do!

Gabriel Walters
Licking Heights Technology Teacher
Gwalters@lhschools.org
